export const floorList = [
    {name: 'Anime', url: '/f/anime'},
    {name: 'Art', url: '/f/art'},
    {name: 'Culture', url: '/f/culture'},
    {name: 'Fitness', url: '/f/fitness'},
    {name: 'Food', url: '/f/food'},
    {name: 'History', url: '/f/history'},
    {name: 'Humor', url: '/f/humor'},
    {name: 'International', url: '/f/international'},
    {name: 'Literature', url: '/f/literature'},
    {name: 'Miscellanous', url: '/f/miscellaneous'},
    {name: 'Movies and TV', url: '/f/moviesandtv'},
    {name: 'Music', url: '/f/music'},
    {name: 'Nature and Wildlife', url: '/f/natureandwildlife'},
    {name: 'Politics', url: '/f/politics'},
    {name: 'Religion', url: '/f/religion'},
    {name: 'Science', url: '/f/science'},
    {name: 'Sports', url: '/f/sports'},
    {name: 'Technology', url: '/f/technology'},
    {name: 'Video Games', url: '/f/videogames'}
]; 